apim_name           = "mssapim2"
apim_location       = "eastus"
resource_group_name = "mss-rg-apim"
sku_tier            = "Developer"
publisher_name      = "Sarfraaz"
publisher_email     = "sarfraaz-nov-24@outlook.com"