swagger: '2.0'
info:
  version: 1.0.0
  title: Health probe
host: not-used-direct-response
basePath: "/"
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  "/":
    get:
      operationId: get-ping
      responses: {}
